pluginManagement {
	repositories {
		maven { url "https://maven.architectury.dev" }
		maven { url "https://maven.neoforged.net/releases" }
		maven { url "https://maven.fabricmc.net" }
		gradlePluginPortal()
	}
}

include "common", "fabric", /*"forge",*/ "neoforge"

rootProject.name = 'FTB-Quests-1.21'
